### ISSUE TITLE
Some static content

### ISSUE THREAD

**Issue by Joknaa** [Ayagoumi/Portfolio#1]
Hey mate, Its good to see ya doing well !
Awesome portfolio 👌🏻 

I noticed one thing that you might've forgot to fix, 
Pressing "Show more" in the projects view shows some static content. And i thought you might wanna fix it.

![image](https://user-images.githubusercontent.com/54961980/149249873-98b507c6-e46d-4c37-babf-306e87049836.png)

Other than that its cool.

**Comment by Ayagoumi** [comment]
Hello there, happy to hear from you.
I am aware of the static content problem, I am working on the 2nd version of my portfolio to replace this one.
